overview:
  title: JavaScript API
  image: logo.png
  description: Learn how to use the JavaScript Pages API with a simple demo.
  order: 10
  facts:
    - JS built FSI Pages
    - JS API Demonstration
schema: bootstrap-taupe
sample:
  menu:
    data: furniture-menu.yml
  featured:
    data: furniture-featured.yml
  highlight: DEAL OF THE DAY
  footer:
    credits:
      photos:
        - author: Artem Bondarchuk
          link: https://unsplash.com/@artembondarchuk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
          platform: Unsplash
      viewer:
        link: https://www.neptunelabs.com/fsi-pages/
  fsi:
    pages: true
  bootstrap:
    icons: true
