overview:
  title: Product Catalog Page
  image: logo.png
  description: Shows how a product catalog page looks.
  order: 1
  facts:
    - JS built FSI Pages
    - interactive catalog
    - including hyperlinks to articles
schema: bootstrap-taupe
sample:
  menu:
    data: furniture-menu.yml
  featured:
    data: furniture-featured.yml
  footer: true
  fsi:
    pages: true
  bootstrap:
    icons: false
